# Generated by Django 3.2.9 on 2022-01-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='posthashtag',
            name='hashtag_is_alphabetic',
        ),
        migrations.RemoveField(
            model_name='posthashtag',
            name='topic',
        ),
        migrations.AlterField(
            model_name='posthashtag',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='name'),
        ),
        migrations.AddConstraint(
            model_name='posthashtag',
            constraint=models.CheckConstraint(check=models.Q(('name__regex', '^[[:alpha:]]+$')), name='hashtag_is_alphabetic'),
        ),
    ]
