# Generated by Django 3.2.9 on 2021-12-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistpost',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nonartistpost',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
