# Generated by Django 3.2.9 on 2022-01-10 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220109_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistpost',
            name='pinned_comment',
            field=models.OneToOneField(blank=True, db_column='pinned_comment_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='posts.artistpostcomment'),
        ),
        migrations.AddField(
            model_name='nonartistpost',
            name='pinned_comment',
            field=models.OneToOneField(blank=True, db_column='pinned_comment_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='posts.nonartistpostcomment'),
        ),
    ]
