# Generated by Django 3.2.9 on 2021-12-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211226_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistpost',
            name='num_comments',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Number of comments'),
        ),
        migrations.AddField(
            model_name='nonartistpost',
            name='num_comments',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Number of comments'),
        ),
        migrations.AddConstraint(
            model_name='artistpostrating',
            constraint=models.CheckConstraint(check=models.Q(('num_stars__gte', 1), ('num_stars__lte', 5)), name='artist_post_rating_stars_betw_1_and_5'),
        ),
        migrations.AddConstraint(
            model_name='nonartistpostrating',
            constraint=models.CheckConstraint(check=models.Q(('num_stars__gte', 1), ('num_stars__lte', 5)), name='non_artist_post_rating_stars_betw_1_and_5'),
        ),
    ]
