# Generated by Django 3.2.9 on 2022-02-04 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220110_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonartistpostrepost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='nonartistpostrepost',
            name='reposter',
        ),
        migrations.RemoveField(
            model_name='artistpost',
            name='num_comment_reposts',
        ),
        migrations.RemoveField(
            model_name='artistpost',
            name='reposters',
        ),
        migrations.RemoveField(
            model_name='artistpostcomment',
            name='is_parent',
        ),
        migrations.RemoveField(
            model_name='nonartistpost',
            name='num_comment_reposts',
        ),
        migrations.RemoveField(
            model_name='nonartistpost',
            name='reposters',
        ),
        migrations.RemoveField(
            model_name='nonartistpostcomment',
            name='is_parent',
        ),
        migrations.AddField(
            model_name='artistpost',
            name='is_simple_repost',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistpost',
            name='num_non_simple_reposts',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Number of reposts with body'),
        ),
        migrations.AddField(
            model_name='artistpost',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_post_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reposts', related_query_name='repost', to='posts.artistpost'),
        ),
        migrations.AddField(
            model_name='nonartistpost',
            name='is_simple_repost',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonartistpost',
            name='num_non_simple_reposts',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Number of reposts with body'),
        ),
        migrations.AddField(
            model_name='nonartistpost',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_post_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reposts', related_query_name='repost', to='posts.nonartistpost'),
        ),
        migrations.AlterField(
            model_name='artistpost',
            name='num_simple_reposts',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Number of reposts without body'),
        ),
        migrations.AlterField(
            model_name='nonartistpost',
            name='num_simple_reposts',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Number of reposts without body'),
        ),
        migrations.DeleteModel(
            name='ArtistPostRepost',
        ),
        migrations.DeleteModel(
            name='NonArtistPostRepost',
        ),
    ]
