# Generated by Django 3.2.9 on 2021-12-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211226_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistpost',
            name='body',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='artistpostrating',
            name='num_stars',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='nonartistpost',
            name='body',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='nonartistpostrating',
            name='num_stars',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
