# Generated by Django 3.2.9 on 2022-02-06 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220204_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistpostcomment',
            options={'ordering': ['-num_likes', '-created_on', '-num_child_comments']},
        ),
        migrations.AlterModelOptions(
            name='nonartistpostcomment',
            options={'ordering': ['-num_likes', '-created_on', '-num_child_comments']},
        ),
        migrations.RemoveField(
            model_name='artistpost',
            name='num_parent_comments',
        ),
        migrations.RemoveField(
            model_name='artistpostcomment',
            name='num_replies',
        ),
        migrations.RemoveField(
            model_name='nonartistpost',
            name='num_parent_comments',
        ),
        migrations.RemoveField(
            model_name='nonartistpostcomment',
            name='num_replies',
        ),
        migrations.AddField(
            model_name='artistpost',
            name='num_ancestor_comments',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Number of ancestor comments'),
        ),
        migrations.AddField(
            model_name='artistpostcomment',
            name='ancestor',
            field=models.ForeignKey(blank=True, db_column='ancestor_comment_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_comments', related_query_name='child_comment', to='posts.artistpostcomment'),
        ),
        migrations.AddField(
            model_name='artistpostcomment',
            name='num_child_comments',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='nonartistpost',
            name='num_ancestor_comments',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Number of ancestor comments'),
        ),
        migrations.AddField(
            model_name='nonartistpostcomment',
            name='ancestor',
            field=models.ForeignKey(blank=True, db_column='ancestor_comment_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_comments', related_query_name='child_comment', to='posts.nonartistpostcomment'),
        ),
        migrations.AddField(
            model_name='nonartistpostcomment',
            name='num_child_comments',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='artistpostcomment',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_comment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', related_query_name='reply', to='posts.artistpostcomment'),
        ),
        migrations.AlterField(
            model_name='nonartistpostcomment',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_comment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', related_query_name='reply', to='posts.nonartistpostcomment'),
        ),
    ]
