# Generated by Django 3.2.9 on 2021-12-27 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20211227_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistpostcomment',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_comment_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', related_query_name='reply', to='posts.artistpostcomment'),
        ),
        migrations.AlterField(
            model_name='nonartistpostcomment',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_comment_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', related_query_name='reply', to='posts.nonartistpostcomment'),
        ),
    ]
