# Generated by Django 3.2.9 on 2021-12-29 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20211227_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistpostcomment',
            options={'ordering': ['-num_likes', '-created_on']},
        ),
        migrations.AlterModelOptions(
            name='nonartistpostcomment',
            options={'ordering': ['-num_likes', '-created_on']},
        ),
    ]
