# Generated by Django 3.2.9 on 2021-12-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20211229_0503'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='posthashtag',
            name='hashtag_is_alphanumeric',
        ),
        migrations.AddConstraint(
            model_name='posthashtag',
            constraint=models.CheckConstraint(check=models.Q(('topic__regex', '^[[:alpha:]]+$')), name='hashtag_is_alphabetic'),
        ),
    ]
