# Generated by Django 3.2.9 on 2022-02-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220211_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistpostcomment',
            name='num_replies',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='nonartistpostcomment',
            name='num_replies',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
