# Generated by Django 3.2.9 on 2021-12-30 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_auto_20211229_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistpostcomment',
            options={'ordering': ['-num_likes', '-created_on', '-num_replies']},
        ),
        migrations.AlterModelOptions(
            name='nonartistpostcomment',
            options={'ordering': ['-num_likes', '-created_on', '-num_replies']},
        ),
        migrations.RemoveConstraint(
            model_name='artistpostrating',
            name='artist_post_rating_stars_betw_1_and_5',
        ),
        migrations.RemoveConstraint(
            model_name='nonartistpostrating',
            name='non_artist_post_rating_stars_betw_1_and_5',
        ),
        migrations.RemoveField(
            model_name='artistpost',
            name='num_comments',
        ),
        migrations.RemoveField(
            model_name='artistpostcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='nonartistpost',
            name='num_comments',
        ),
        migrations.RemoveField(
            model_name='nonartistpostcomment',
            name='post',
        ),
        migrations.AddField(
            model_name='artistpost',
            name='num_parent_comments',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Number of parent comments'),
        ),
        migrations.AddField(
            model_name='artistpostcomment',
            name='is_parent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='artistpostcomment',
            name='num_replies',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='artistpostcomment',
            name='post_concerned',
            field=models.ForeignKey(db_column='artist_post_concerned_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='overall_comments', related_query_name='comment', to='posts.artistpost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonartistpost',
            name='num_parent_comments',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Number of parent comments'),
        ),
        migrations.AddField(
            model_name='nonartistpostcomment',
            name='is_parent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nonartistpostcomment',
            name='num_replies',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='nonartistpostcomment',
            name='post_concerned',
            field=models.ForeignKey(db_column='non_artist_post_concerned_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='overall_comments', related_query_name='comment', to='posts.nonartistpost'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artistpostcomment',
            name='poster',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='overall_artist_post_comments', related_query_name='artist_post_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nonartistpostcomment',
            name='poster',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='overall_non_artist_post_comments', related_query_name='non_artist_post_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posthashtag',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AddConstraint(
            model_name='artistpostrating',
            constraint=models.CheckConstraint(check=models.Q(('num_stars', 1), ('num_stars', 3), ('num_stars', 5), _connector='OR'), name='artist_post_rating_stars_is_1_or_3_or_5'),
        ),
        migrations.AddConstraint(
            model_name='nonartistpostrating',
            constraint=models.CheckConstraint(check=models.Q(('num_stars', 1), ('num_stars', 3), ('num_stars', 5), _connector='OR'), name='non_artist_post_rating_stars_is_1_or_3_or_5'),
        ),
    ]
