# Generated by Django 3.2.9 on 2022-02-12 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220211_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistpost',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_post_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', related_query_name='repost', to='posts.artistpost'),
        ),
        migrations.AlterField(
            model_name='nonartistpost',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_post_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', related_query_name='repost', to='posts.nonartistpost'),
        ),
    ]
