# Generated by Django 3.2.9 on 2022-01-01 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20211230_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistpost',
            old_name='updated_on',
            new_name='last_updated_on',
        ),
        migrations.RenameField(
            model_name='artistpostcomment',
            old_name='updated_on',
            new_name='last_updated_on',
        ),
        migrations.RenameField(
            model_name='nonartistpost',
            old_name='updated_on',
            new_name='last_updated_on',
        ),
        migrations.RenameField(
            model_name='nonartistpostcomment',
            old_name='updated_on',
            new_name='last_updated_on',
        ),
    ]
