# Generated by Django 3.2.9 on 2022-01-02 19:23

import core.fields
import django.core.validators
from django.db import migrations, models
import easy_thumbnails.fields
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20220101_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistpostphoto',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(height_field='photo_height', upload_to='artist_posts_photos/', validators=[django.core.validators.FileExtensionValidator(['png, jpg, gif']), posts.validators.validate_post_photo], width_field='photo_width'),
        ),
        migrations.AlterField(
            model_name='artistpostphoto',
            name='photo_height',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='artistpostphoto',
            name='photo_width',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='artistpostvideo',
            name='video',
            field=core.fields.DynamicStorageFileField(blank=True, upload_to='artist_posts_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov']), posts.validators.validate_post_video]),
        ),
        migrations.AlterField(
            model_name='nonartistpostphoto',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(height_field='photo_height', upload_to='non_artist_posts_photos/', validators=[django.core.validators.FileExtensionValidator(['png, jpg, gif']), posts.validators.validate_post_photo], width_field='photo_width'),
        ),
        migrations.AlterField(
            model_name='nonartistpostphoto',
            name='photo_height',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='nonartistpostphoto',
            name='photo_width',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='nonartistpostvideo',
            name='video',
            field=core.fields.DynamicStorageFileField(blank=True, upload_to='artist_posts_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov']), posts.validators.validate_post_video]),
        ),
    ]
