# Generated by Django 3.2.9 on 2022-02-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20220221_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistParentPost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('posts.artistpost',),
        ),
        migrations.CreateModel(
            name='ArtistPostRepost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('posts.artistpost',),
        ),
        migrations.CreateModel(
            name='NonArtistParentPost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('posts.nonartistpost',),
        ),
        migrations.CreateModel(
            name='NonArtistPostRepost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('posts.nonartistpost',),
        ),
        migrations.AddIndex(
            model_name='artistpost',
            index=models.Index(fields=['is_simple_repost'], name='artist_post_repost_idx'),
        ),
        migrations.AddIndex(
            model_name='nonartistpost',
            index=models.Index(fields=['is_simple_repost'], name='non_artist_post_repost_idx'),
        ),
    ]
