# Generated by Django 3.2.9 on 2022-01-03 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20220102_1923'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='posthashtag',
            name='hashtag_is_alphabetic',
        ),
    ]
