# Generated by Django 3.2.9 on 2022-01-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_posthashtag_hashtag_is_alphabetic'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='posthashtag',
            constraint=models.CheckConstraint(check=models.Q(('topic__regex', '^[[:alpha:]]+$')), name='hashtag_is_alphabetic'),
        ),
    ]
