# Generated by Django 3.2.9 on 2022-02-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20220226_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistpostvideo',
            name='num_views',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='nonartistpostvideo',
            name='num_views',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
