# Generated by Django 3.2.9 on 2022-01-04 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0013_posthashtag_hashtag_is_alphabetic'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonArtistPostCommentMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(db_column='non_artist_post_comment_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='posts.nonartistpostcomment')),
                ('user_mentioned', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'posts"."non_artist_post_comment_user_mention',
            },
        ),
        migrations.CreateModel(
            name='ArtistPostCommentMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(db_column='artist_post_comment_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='posts.artistpostcomment')),
                ('user_mentioned', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'posts"."artist_post_comment_user_mention',
            },
        ),
        migrations.AddField(
            model_name='artistpostcomment',
            name='users_mentioned',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_artist_post_comment', related_query_name='mentioned_in_artist_post_comment', through='posts.ArtistPostCommentMention', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nonartistpostcomment',
            name='users_mentioned',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_non_artist_post_comment', related_query_name='mentioned_in_non_artist_post_comment', through='posts.NonArtistPostCommentMention', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='nonartistpostcommentmention',
            constraint=models.UniqueConstraint(fields=('comment', 'user_mentioned'), name='unique_non_artist_post_comment_user_mention'),
        ),
        migrations.AddConstraint(
            model_name='artistpostcommentmention',
            constraint=models.UniqueConstraint(fields=('comment', 'user_mentioned'), name='unique_artist_post_comment_user_mention'),
        ),
    ]
