# Generated by Django 3.2.9 on 2022-03-12 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20220227_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistpost',
            name='pinned_comment',
            field=models.OneToOneField(blank=True, db_column='pinned_comment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='posts.artistpostcomment'),
        ),
        migrations.AlterField(
            model_name='nonartistpost',
            name='pinned_comment',
            field=models.OneToOneField(blank=True, db_column='pinned_comment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='posts.nonartistpostcomment'),
        ),
    ]
