# Generated by Django 3.2.9 on 2021-12-29 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import flagging.models.operations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('state', models.SmallIntegerField(choices=[(1, 'Unflagged'), (2, 'Flagged'), (3, 'Flag rejected by the moderator'), (5, 'Content modified by the author'), (4, 'Creator notified')], default=1)),
                ('count', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags_against', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags_moderated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flag',
                'db_table': 'flagging"."flag',
            },
            bases=(models.Model, flagging.models.operations.FlagOperations),
        ),
        migrations.CreateModel(
            name='FlagInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_flagged', models.DateTimeField(auto_now_add=True)),
                ('reason', models.SmallIntegerField(choices=[(1, 'Spam | Exists only to promote a service '), (2, 'Abusive | Intended at promoting hatred'), (100, 'Something else')], default=1)),
                ('info', models.TextField(blank=True)),
                ('flag', models.ForeignKey(db_column='flag_id', on_delete=django.db.models.deletion.CASCADE, related_name='flags', related_query_name='flag_instance', to='flagging.flag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_flag_instances', related_query_name='flag_instance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flag Instance',
                'verbose_name_plural': 'Flag Instances',
                'db_table': 'flagging"."flag_instance',
                'ordering': ['-date_flagged'],
            },
        ),
        migrations.AddIndex(
            model_name='flaginstance',
            index=models.Index(fields=['-date_flagged'], name='flag_instance_date_desc_idx'),
        ),
        migrations.AddConstraint(
            model_name='flaginstance',
            constraint=models.UniqueConstraint(fields=('flag', 'user'), name='unique_user_and_flag_instance'),
        ),
        migrations.AddConstraint(
            model_name='flag',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_content_type_and_object_id'),
        ),
    ]
