# Generated by Django 3.1.3 on 2021-11-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flagging', '0002_auto_20211017_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaginstance',
            name='info',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
