# Generated by Django 3.2.9 on 2022-01-09 03:07

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pinned_artist_post',
            field=models.OneToOneField(blank=True, db_column='pinned_artist_post_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='posts.artistpost'),
        ),
        migrations.AddField(
            model_name='user',
            name='pinned_non_artist_post',
            field=models.OneToOneField(blank=True, db_column='pinned_non_artist_post_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='posts.nonartistpost'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='userfollow',
            constraint=models.UniqueConstraint(fields=('follower', 'following'), name='unique_user_follow'),
        ),
        migrations.AddConstraint(
            model_name='userfollow',
            constraint=models.CheckConstraint(check=models.Q(('follower', django.db.models.expressions.F('following')), _negated=True), name='cannot_follow_self'),
        ),
        migrations.AddConstraint(
            model_name='userblocking',
            constraint=models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_user_blocking'),
        ),
        migrations.AddConstraint(
            model_name='userblocking',
            constraint=models.CheckConstraint(check=models.Q(('blocker', django.db.models.expressions.F('blocked')), _negated=True), name='cannot_block_self'),
        ),
        migrations.AddConstraint(
            model_name='artistfollow',
            constraint=models.UniqueConstraint(fields=('follower', 'artist'), name='unique_user_artist_follow'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('username',), include=('display_name',), name='unique_username'),
        ),
    ]
