# Generated by Django 3.2.9 on 2021-12-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_photo',
            field=models.ImageField(blank=True, height_field='cover_photo_height', upload_to='', verbose_name='Cover photo', width_field='cover_photo_width'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_photo_height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_photo_width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, height_field='profile_photo_height', upload_to='', verbose_name='Profile photo', width_field='profile_photo_width'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo_height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo_width',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
