# Generated by Django 3.2.9 on 2021-12-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211223_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='num_posts',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
