# Generated by Django 3.2.9 on 2022-02-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220131_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='num_parent_artist_post_comments',
            new_name='num_ancestor_artist_post_comments',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='num_parent_non_artist_post_comments',
            new_name='num_ancestor_non_artist_post_comments',
        ),
        migrations.AddField(
            model_name='user',
            name='num_artist_post_reposts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='num_non_artist_post_reposts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
