# Generated by Django 3.2.9 on 2021-12-24 02:58

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_artist_num_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(editable=False, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='artisttag',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_collation='accounts"."case_insensitive', editable=False, error_messages={'unique': 'A user with that username already exists.'}, help_text='Your username should be less than 15 characters.', max_length=15, validators=[accounts.validators.UserUsernameValidator()], verbose_name='Username'),
        ),
    ]
