# Generated by Django 3.2.9 on 2022-02-07 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220206_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspension',
            name='suspender',
            field=models.ForeignKey(db_column='suspender_user_id', default=2, on_delete=django.db.models.deletion.CASCADE, related_name='suspended_users', related_query_name='suspension', to='accounts.user'),
            preserve_default=False,
        ),
    ]
