# Generated by Django 3.2.9 on 2021-12-26 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211226_0245'),
        ('accounts', '0004_auto_20211224_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pinned_artist_post',
            field=models.OneToOneField(blank=True, db_column='pinned_artist_post_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='posts.artistpost'),
        ),
        migrations.AddField(
            model_name='user',
            name='pinned_non_artist_post',
            field=models.OneToOneField(blank=True, db_column='pinned_non_artist_post_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='posts.nonartistpost'),
        ),
    ]
