# Generated by Django 3.2.9 on 2021-12-26 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211226_0322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='num_artist_related_post_comments',
            new_name='num_artist_post_comments',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='num_artist_related_posts',
            new_name='num_artist_posts',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='num_non_artist_related_post_comments',
            new_name='num_non_artist_post_comments',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='num_non_artist_related_posts',
            new_name='num_non_artist_posts',
        ),
    ]
