# Generated by Django 3.2.9 on 2022-02-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_suspension_suspender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='num_ancestor_artist_post_comments',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='num_ancestor_non_artist_post_comments',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='num_artist_post_reposts',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='num_artist_posts',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='num_followers',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='num_following',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='num_non_artist_post_reposts',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='num_non_artist_posts',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
