# Generated by Django 3.2.9 on 2022-02-09 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220209_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggedartist',
            name='content_object',
            field=models.ForeignKey(db_column='artist_id', on_delete=django.db.models.deletion.CASCADE, related_name='tagged_artists', related_query_name='tagged_artist', to='accounts.artist'),
        ),
        migrations.AlterField(
            model_name='taggedartist',
            name='tag',
            field=models.ForeignKey(db_column='artist_tag_id', on_delete=django.db.models.deletion.CASCADE, related_name='tagged_artists', related_query_name='tagged_artist', to='accounts.artisttag'),
        ),
    ]
