# Generated by Django 3.2.9 on 2021-12-26 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='date_of_birth',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='date_of_birth',
            new_name='birth_date',
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, help_text='Write about yourself & taste for music. You may include your favorite artists or songs.', max_length=150, verbose_name='Bio'),
        ),
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.CheckConstraint(check=models.Q(('birth_date__lte', datetime.date(2006, 12, 30)), ('birth_date__gte', datetime.date(1922, 1, 20))), name='age_gte_15_and_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('birth_date__lte', datetime.date(2008, 12, 29)), ('birth_date__gte', datetime.date(1902, 1, 25))), name='age_gte_13_and_lte_120'),
        ),
    ]
