# Generated by Django 3.2.9 on 2022-02-09 10:44

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220209_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='accounts.TaggedArtist', to='accounts.ArtistTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='taggedartist',
            name='content_object',
            field=models.ForeignKey(db_column='artist_id', on_delete=django.db.models.deletion.CASCADE, related_name='tagged_tags', related_query_name='tagged_tag', to='accounts.artist'),
        ),
    ]
