# Generated by Django 3.2.9 on 2021-12-27 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211226_1738'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='artist',
            name='age_gte_15_and_lte_100',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='age_gte_13_and_lte_120',
        ),
        migrations.RenameField(
            model_name='suspension',
            old_name='period',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='suspension',
            old_name='suspended_on',
            new_name='given_on',
        ),
        migrations.AddField(
            model_name='suspension',
            name='reason',
            field=models.CharField(choices=[('SP', 'Spam'), ('AB', 'Abusive/Hate speech')], default='AB', max_length=2),
        ),
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.CheckConstraint(check=models.Q(('birth_date__lte', datetime.date(2006, 12, 31)), ('birth_date__gte', datetime.date(1922, 1, 21))), name='age_gte_15_and_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('birth_date__lte', datetime.date(2008, 12, 30)), ('birth_date__gte', datetime.date(1902, 1, 26))), name='age_gte_13_and_lte_120'),
        ),
    ]
