# Generated by Django 3.2.9 on 2022-02-11 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220209_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggedartist',
            name='tag',
            field=models.ForeignKey(db_column='artist_tag_id', on_delete=django.db.models.deletion.CASCADE, related_name='tagged_artists', to='accounts.artisttag'),
        ),
    ]
