# Generated by Django 3.2.9 on 2021-12-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211227_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisttag',
            name='slug',
            field=models.SlugField(editable=False, max_length=30, unique=True),
        ),
        migrations.AddConstraint(
            model_name='artisttag',
            constraint=models.CheckConstraint(check=models.Q(('name__regex', '^[a-zA-ZÀ-Ÿ0-9]+$'), _negated=True), name='tag_is_alphanumeric'),
        ),
    ]
