# Generated by Django 3.2.9 on 2022-02-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220211_1041'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_superuser'], name='user_is_superuser_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_staff'], name='user_is_staff_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_mod'], name='user_is_mod_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='user_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_verified'], name='user_is_verified_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_premium'], name='user_is_premium_idx'),
        ),
    ]
