# Generated by Django 3.2.9 on 2021-12-29 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20211227_1659'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='artist',
            name='age_gte_15_and_lte_100',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='age_gte_13_and_lte_120',
        ),
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.CheckConstraint(check=models.Q(('birth_date__lte', datetime.date(2007, 1, 2)), ('birth_date__gte', datetime.date(1922, 1, 23))), name='age_gte_15_and_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('birth_date__lte', datetime.date(2009, 1, 1)), ('birth_date__gte', datetime.date(1902, 1, 28))), name='age_gte_13_and_lte_120'),
        ),
    ]
