# Generated by Django 3.2.9 on 2021-12-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20211229_0503'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='artisttag',
            name='tag_is_alphanumeric',
        ),
        migrations.AddConstraint(
            model_name='artisttag',
            constraint=models.CheckConstraint(check=models.Q(('name__regex', '^[[:alpha:]]+$')), name='artist_tag_is_alphabetic'),
        ),
    ]
