# Generated by Django 3.2.9 on 2021-12-30 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20211229_1402'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='artist',
            name='age_gte_15_and_lte_100',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='age_gte_13_and_lte_120',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='num_artist_post_comments',
            new_name='num_parent_artist_post_comments',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='num_non_artist_post_comments',
            new_name='num_parent_non_artist_post_comments',
        ),
        migrations.AlterField(
            model_name='artisttag',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.CheckConstraint(check=models.Q(('birth_date__lte', datetime.date(2007, 1, 3)), ('birth_date__gte', datetime.date(1922, 1, 24))), name='age_gte_15_and_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('birth_date__lte', datetime.date(2009, 1, 2)), ('birth_date__gte', datetime.date(1902, 1, 29))), name='age_gte_13_and_lte_120'),
        ),
    ]
