# Generated by Django 3.2.9 on 2022-02-27 04:38

import accounts.models.users.models
import accounts.validators
import django.core.validators
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20220226_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, height_field='cover_photo_height', upload_to=accounts.models.users.models.cover_photo_upload_path, validators=[django.core.validators.FileExtensionValidator(['png, jpg'])], width_field='cover_photo_width'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, height_field='profile_picture_height', upload_to=accounts.models.users.models.profile_pic_upload_path, validators=[django.core.validators.FileExtensionValidator(['png, jpg']), accounts.validators.validate_profile_and_cover_photo], width_field='profile_picture_width'),
        ),
    ]
