# Generated by Django 3.2.9 on 2022-02-27 15:50

import accounts.models.artists.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20220227_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistphoto',
            name='uploaded_by',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_artist_photos', related_query_name='artist_photo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artistphoto',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(height_field='photo_height', upload_to=accounts.models.artists.models.get_artist_photo_upload_path, validators=[django.core.validators.FileExtensionValidator(['png, jpg'])], width_field='photo_width'),
        ),
    ]
