# Generated by Django 3.2.9 on 2022-01-01 14:24

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20211230_1536'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='artist',
            name='age_gte_15_and_lte_100',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='age_gte_13_and_lte_120',
        ),
        migrations.AddConstraint(
            model_name='userblocking',
            constraint=models.CheckConstraint(check=models.Q(('blocker', django.db.models.expressions.F('blocked')), _negated=True), name='cannot_block_self'),
        ),
        migrations.AddConstraint(
            model_name='userfollow',
            constraint=models.CheckConstraint(check=models.Q(('follower', django.db.models.expressions.F('following')), _negated=True), name='cannot_follow_self'),
        ),
    ]
