# Generated by Django 3.2.9 on 2022-03-12 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20220312_0541'),
        ('accounts', '0014_auto_20220227_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pinned_artist_post',
            field=models.OneToOneField(blank=True, db_column='pinned_artist_post_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='posts.artistpost'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pinned_non_artist_post',
            field=models.OneToOneField(blank=True, db_column='pinned_non_artist_post_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='posts.nonartistpost'),
        ),
    ]
