# Generated by Django 3.2.9 on 2022-01-02 19:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20220101_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistphoto',
            options={'ordering': ['-uploaded_on']},
        ),
        migrations.RenameField(
            model_name='artistphoto',
            old_name='added_on',
            new_name='uploaded_on',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profile_photo_height',
            new_name='profile_picture_height',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profile_photo_width',
            new_name='profile_picture_width',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, height_field='profile_picture_height', upload_to='profile_pictures/', validators=[django.core.validators.FileExtensionValidator(['png, jpg'])], width_field='profile_picture_width'),
        ),
        migrations.AlterField(
            model_name='artistphoto',
            name='artist',
            field=models.ForeignKey(db_column='artist_id', on_delete=django.db.models.deletion.CASCADE, related_name='photos', related_query_name='photo', to='accounts.artist'),
        ),
        migrations.AlterField(
            model_name='artistphoto',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(height_field='photo_height', upload_to='artists_photos/', validators=[django.core.validators.FileExtensionValidator(['png, jpg, gif'])], width_field='photo_width'),
        ),
        migrations.AlterField(
            model_name='artistphoto',
            name='photo_height',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='artistphoto',
            name='photo_width',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, height_field='cover_photo_height', upload_to='cover_photos/', width_field='cover_photo_width'),
        ),
    ]
