# Generated by Django 3.2.9 on 2022-01-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20220102_1923'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='artisttag',
            name='artist_tag_is_alphabetic',
        ),
        migrations.AlterField(
            model_name='artist',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AddConstraint(
            model_name='artisttag',
            constraint=models.CheckConstraint(check=models.Q(('name__regex', '^[[:alpha:]]+(?:[[:space:]][[:alpha:]]+)*$')), name='artist_tag_is_alphabetic'),
        ),
    ]
