# Generated by Django 3.2.9 on 2022-01-03 20:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20220103_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 3, 20, 35, 39, 646860, tzinfo=utc), verbose_name='Date of birth'),
            preserve_default=False,
        ),
    ]
