# Generated by Django 3.2.9 on 2022-01-03 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_artist_birth_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='artisttag',
            name='artist_tag_is_alphabetic',
        ),
    ]
