# Generated by Django 3.2.9 on 2022-01-04 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_artisttag_artist_tag_is_alphabetic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_on', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(db_column='artist_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.artist')),
                ('follower', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts"."artist_follow',
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='followers',
            field=models.ManyToManyField(related_name='following_artists', related_query_name='following_artist', through='accounts.ArtistFollow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='artistfollow',
            constraint=models.UniqueConstraint(fields=('follower', 'artist'), name='unique_user_artist_follow'),
        ),
    ]
