# Generated by Django 3.2.9 on 2022-01-09 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import notifications.models.operations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('S', 'Success'), ('I', 'Info'), ('W', 'Warning'), ('E', 'Error')], default='I', max_length=2)),
                ('category', models.CharField(choices=[('G', 'General'), ('A', 'Account'), ('M', 'Mention'), ('F', 'Flag'), ('FO', 'Follow'), ('R', 'Reported to moderator'), ('RA', 'Post rating'), ('C', 'Comment'), ('RP', 'Repost'), ('CL', 'Comment like'), ('D', 'Flagged content deleted')], max_length=2)),
                ('actor_object_id', models.CharField(max_length=255)),
                ('verb', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_object_id', models.CharField(blank=True, max_length=255)),
                ('action_object_object_id', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('unread', models.BooleanField(default=True)),
                ('emailed', models.BooleanField(default=False)),
                ('action_object_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_action_object', to='contenttypes.contenttype')),
                ('actor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_actor', to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(db_column='recipient_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', related_query_name='notification', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_target', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'notifications"."notification',
                'ordering': ['-timestamp'],
            },
            bases=(models.Model, notifications.models.operations.NotificationOperations),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-timestamp'], name='notif_timestamp_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'unread'], name='notif_recipient_and_unread_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['unread', 'emailed'], name='notif_unread_and_emailed_idx'),
        ),
    ]
