# Generated by Django 3.2.9 on 2022-02-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('G', 'General'), ('A', 'Account'), ('M', 'Mention'), ('F', 'Flag'), ('FO', 'Follow'), ('R', 'Reported to moderator or staff'), ('RA', 'Post rating'), ('C', 'Comment'), ('RP', 'Repost'), ('CL', 'Comment like'), ('CR', 'Comment reply'), ('D', 'Flagged content deleted')], max_length=2),
        ),
    ]
